# Be sure to set up the $_PORT, $_REPO and $_SERVICE_NAME variables
# when configuring the Cloud Build Trigger
#
# Also, be sure the service account in Cloud Build has the "Cloud Functions Admin" role
# in order to set the service as "unauthenticated" when deploying

steps:
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE_NAME:$COMMIT_SHA', '.' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE_NAME:$COMMIT_SHA' ]
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args:
    - run
    - deploy
    - $_SERVICE_NAME
    - '--image'
    - '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE_NAME:$COMMIT_SHA'
    - '--region'
    - $LOCATION
    - '--port'
    - '$_PORT'
    - '--allow-unauthenticated'
  entrypoint: gcloud
timeout: 1200s
images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE_NAME:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
